// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6312_9VHGr9uP0cyA7j90yKgy_GfwGU',
    appId: '1:736146420628:web:5f9db4ba05460d9b5c9581',
    messagingSenderId: '736146420628',
    projectId: 'gspproject-d4474',
    authDomain: 'gspproject-d4474.firebaseapp.com',
    storageBucket: 'gspproject-d4474.firebasestorage.app',
    measurementId: 'G-Q6YG9WZXXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS87XXIZ_8ZsZM6ZxXZC6CqoUybKbEse4',
    appId: '1:96559250103:android:18c4f34ba059126bf5eb32',
    messagingSenderId: '96559250103',
    projectId: 'gspappv2',
    storageBucket: 'gspappv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkywGrp5cecceQHHnM-VtjsseV8m9Ygw',
    appId: '1:96559250103:ios:a329b26693cb0a82f5eb32',
    messagingSenderId: '96559250103',
    projectId: 'gspappv2',
    storageBucket: 'gspappv2.firebasestorage.app',
    iosBundleId: 'com.example.gspappv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkywGrp5cecceQHHnM-VtjsseV8m9Ygw',
    appId: '1:96559250103:ios:a329b26693cb0a82f5eb32',
    messagingSenderId: '96559250103',
    projectId: 'gspappv2',
    storageBucket: 'gspappv2.firebasestorage.app',
    iosBundleId: 'com.example.gspappv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYJX9QYphWQTmiuE0bgWCsVGePm3hdM00',
    appId: '1:96559250103:web:de521926e4fee897f5eb32',
    messagingSenderId: '96559250103',
    projectId: 'gspappv2',
    authDomain: 'gspappv2.firebaseapp.com',
    storageBucket: 'gspappv2.firebasestorage.app',
  );
}